services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mmorpg_catalog
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d mmorpg_catalog"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Point Spring to the db service hostname "db"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mmorpg_catalog
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  pgdata:
